### ISSUE TITLE
Introduce shallow and deep tags

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-healthcheck#10]
Other than health check type tags, we also need to introduce health check level tags.

* `shallow` will be executed very frequently (think an ELB doing a heartbeat), it should be minimum check that indicates that AEM is healthy, it shouldn't consume much resource on the server

* `deep` will be executed less frequent, it should give high level of confidence that AEM is healthy, it can consume some resource but obviously not to cause AEM itself to struggle

**Comment by lenuhc** [comment]
Closed with PR #12
