### ISSUE TITLE
Health check needs to be accessible without authentication

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-healthcheck#7]
/system/health currently requires authentication (responds with 401 if none supplied), which is not always possible, e.g. when the health check is meant to be performed from an ELB - we can't put any credential in plain text there.

Hence we need to be able to access the health check without authentication.

**Comment by mickleroy** [comment]
Fixed in [release 1.3](https://github.com/shinesolutions/aem-healthcheck/releases/tag/v1.3)
